### ISSUE TITLE
Everspring Plug Adapter request

### ISSUE THREAD

**Issue by Rubelke** [ralfvd/com.everspring#1]
Hello Ralf,

Great that you made a everspring app.
I have a Everspring Plug Adapter (AN181 - Mini On/Off Plug with Power Metering) and it would be great if we could implement it in your app.
I dont know how to do it, which information do you need to get it work?

**Comment by posthok** [comment]
Could you also add the Socket dimmer?

EVERSPRING TUSSENSTEKKER DIMMER MET Z-WAVE PLUS
SKU: EVR_AD1472

I have the following settings in Domoticz.


1. Basic Set Command value:  (huidig: 99)

0 is off. 1 to 99 sets output level at specified value. 255 sets output level at last memorized level
Last Update: 2016-07-20 14:17:31

2. Delay Time:  (seconds) (huidig: 3)

Delaying time to report to Group 1
Last Update: 2016-07-20 14:17:31

3. Last Status:  (huidig: 0)

Remember the last status: 0 (do not remember) | 1 (remember)
Last Update: 2016-07-20 14:17:31

4. Output Mode:  (huidig: 0)

Output mode setting: 0 (dimming) | 1 (on/off)
![evr_ad1472-zwave-plus-logo](https://cloud.githubusercontent.com/assets/6661318/17395856/c7b4d84c-5a30-11e6-8ad5-e4bf945214f3.png)

**Comment by ralfvd** [comment]
Implemented, although AD1422 now has some issues with recent Homey firmware. A separate issue exists for this
