### ISSUE TITLE
Feature request: support Wall Plug Switch AN1572

### ISSUE THREAD

**Issue by irritanterik** [ralfvd/com.everspring#11]
I would love support for the on/off wall plug AN1572

After pairing Homey now add this as a generic z-wave device. Info:
![image](https://cloud.githubusercontent.com/assets/15232724/22489186/56ec60ca-e816-11e6-9f3b-3e83b7a171ba.png)

**Comment by ralfvd** [comment]
@irritanterik I've added the AN157 device, but don't have the device myself, so couldn't test it. Can you test from the GitHub source ? Let me know if it works for you ( control it via Homey and get correct state reported if you use the on/off button on the AN157 itself).

**Comment by irritanterik** [comment]
Great! I am able to test the git version of the app later this week.

**Comment by ralfvd** [comment]
@irritanterik Did you have a chance to test it? Then i can add the update to the app store. Thanks!

**Comment by ralfvd** [comment]
AN157 implemented and release in app store
