### ISSUE TITLE
sp103 not detecting motion and manual install app fails

### ISSUE THREAD

**Issue by B3rt** [ralfvd/com.everspring#13]
SP103 does not dtect montion anymore and i tried to update to version 0.1.9 nually, sadly this version crashes on Homey:

C:\Users\r\Downloads\com.everspring-master\com.everspring-master>athom project --install
? Select active Homey: Homey @ 192.168.1.4:80
1/3 - Archiving...
2/3 - Uploading to Homey @ 192.168.1.4:80...
3/3 - Installed `com.everspring`

C:\Users\r\Downloads\com.everspring-master\com.everspring-master>

Stack trace:

Error: Cannot find module 'homey-zwavedriver'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/drivers/AN180/driver.js:4:21)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)

Exit code: undefined
Exit signal: undefined

How can i fix this?

**Comment by ralfvd** [comment]
You need to add the homey-zwavedriver in the 'node-modules' directory. You can download the driver here: https://github.com/athombv/node-homey-zwavedriver/

After that, installation should be OK.

**Comment by B3rt** [comment]
sadly no instructions how to do this..

I cannot get those drivers installed..

**Comment by ralfvd** [comment]
Go to : https://github.com/athombv/node-homey-zwavedriver/

click on green button Clone/Download , then download as ZIP.

Extract the zip file in C:\Users\r\Downloads\com.everspring-master\com.everspring-master\node_modules\homey-zwavedriver\

After this, an athom project --install should work.

**Comment by ralfvd** [comment]
0.1.9 just got approved by Athom, so you can just do a normal 'app store' install. Or wait a couple of hours for Homey to detect and upgrade automatically.

Let me know if you still have issues with 0.1.9 . Sorry for the inconvenience!
