### ISSUE TITLE
Please add ST812 - Wireless Flood Detector

### ISSUE THREAD

**Issue by sjaakie33** [ralfvd/com.everspring#14]
Good day,

Please add ST812 - Wireless Flood Detector

With kind regards

René Ardley

**Comment by djanssen1** [comment]
Yes. please add support. I'm having this sensor as well and ready to test it

Manufacturer ID: 96
Product Type ID: 11
Product ID: 1

**Comment by ralfvd** [comment]
Added to Todo list


-------- Original Message --------

**Comment by ralfvd** [comment]
Code for ST812 is now available on GitHub. If you are able, please test it with the Athom CLI and if it is not working, let me know, so we can look at the debug output to see what is wrong in the code.

Thanks.

**Comment by sjaakie33** [comment]
Good day,

tested and is working properly

Thanks

**Comment by goyaweb** [comment]
would be great if you could submit it to the appstore as beta

**Comment by ralfvd** [comment]
It is now available as Beta in the App store. Please install and let me know the results.

**Comment by goyaweb** [comment]
great it works! thanks!
