### ISSUE TITLE
Please add AD146 In-Wall DIMMER module

### ISSUE THREAD

**Issue by muaki** [ralfvd/com.everspring#19]
Found some information here:
http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/24
https://github.com/openhab/openhab1-addons/blob/master/bundles/binding/org.openhab.binding.zwave/database/everspring/ad146.xml

**Comment by jolny** [comment]
Hi @muaki , I've added support in Pull Request #20 .

However, the code needs to be tested before it can be merged. Can you do that?
Direct link to my code: https://github.com/jolny/com.everspring/archive/master.zip
How to run: https://apps.developer.athom.com/tutorial-Getting%20Started.html

After you press CTRL+C the experimental  app will be uninstalled.

**Comment by jolny** [comment]
Hi again, the dimmer has now been tested so hopefully my Pull request will be accepted shortly, and the app updated to include the AD146.

**Comment by ralfvd** [comment]
Available in 0.2.3

**Comment by ralfvd** [comment]
Thanks for the contribution!

**Comment by muaki** [comment]
Thank you so much, works perfect!!
