### ISSUE TITLE
No updates

### ISSUE THREAD

**Issue by florisi** [ralfvd/com.everspring#2]
Installed your app.
That part is ok.
But I never recieve any updates from the device.
Running 0.9.2 on Homey

**Comment by ralfvd** [comment]
This is concerning the ST-814 device. In progress

**Comment by ralfvd** [comment]
I am getting pretty regular updates now from the ST814 , do you still have this issue?

Fri Jan 06 2017 02:58:03 GMT+0100 (CET),16.4
Fri Jan 06 2017 03:25:24 GMT+0100 (CET),16.3
Fri Jan 06 2017 03:57:02 GMT+0100 (CET),16.2
Fri Jan 06 2017 06:33:48 GMT+0100 (CET),17
Fri Jan 06 2017 07:01:12 GMT+0100 (CET),17.1
Fri Jan 06 2017 07:18:21 GMT+0100 (CET),17
Fri Jan 06 2017 08:39:33 GMT+0100 (CET),17.1
Fri Jan 06 2017 11:36:38 GMT+0100 (CET),16.9
Fri Jan 06 2017 12:34:14 GMT+0100 (CET),16.6
Fri Jan 06 2017 15:09:12 GMT+0100 (CET),16.1
Fri Jan 06 2017 17:24:42 GMT+0100 (CET),16
Fri Jan 06 2017 18:11:34 GMT+0100 (CET),16.3
Fri Jan 06 2017 22:15:04 GMT+0100 (CET),17.2
