### ISSUE TITLE
Please add HSM02 door\window

### ISSUE THREAD

**Issue by igitlin** [ralfvd/com.everspring#23]
https://products.z-wavealliance.org/products/14
https://products.z-wavealliance.org/products/607
http://www.ctc-chromagic.com/?q=zwave/HSM02
http://www.everspring.com/portfolio-item/hsm02-mini-door-window-contact-detector/

**Comment by ralfvd** [comment]
Code (as written by yourself ;-) is now pending approval in the app store. Thanks for the contribution!
