### ISSUE TITLE
Feature request: Actioncard for dimmer that accept a variable as a value

### ISSUE THREAD

**Issue by dicknystrand** [ralfvd/com.everspring#25]
I have e few AD147 dimmer plugs that I want to be able to set with a variable (Better Logic). 
For now I have to set the value by scrolling. 

![image](https://user-images.githubusercontent.com/37040361/37518734-b0d6e8e8-2916-11e8-9052-74fac073c6db.png)

**Comment by ralfvd** [comment]
Unfortunately, there cannot be a manual input for dimming lights. But there is a way that works pretty good: you can drop a global tag into the slider, like this:

![screen shot 2018-03-27 at 21 18 50](https://user-images.githubusercontent.com/17275712/37989709-86867ee0-3204-11e8-867c-edb14ac136df.png)

You need to make sure that the value is between 0 - 0.99 , so if you want to dim to 50 % , the value of the global tag needs to be 0.50 . 

Let me know if this helps in your request.
