### ISSUE TITLE
Everspring does not work with Homey 5.0.0

### ISSUE THREAD

**Issue by roger-lindahl** [ralfvd/com.everspring#45]
Hi!

I enabled experimental updates on my Homey (Early 2018) and recieved firmware 5.0.0. But now my Nexa switch AD-147 (z-wave) does not work. I have hade the app "everspring" installed for the switch (with dimmer). I have tried uninstalling the app but no luck. When I try to enable the app in "apps" the error message is: "SDK version is not supported, make sure the SDK version in your app.json manifest is correct". What can be done to fix this?

/WBR Roger Lindahl

**Comment by roger-lindahl** [comment]
HI Ralf!

I had a supportcase in Homey support and they told me this as a message to you: 

Please inform the developer that the SDK that he uses for his app is outdated and his app requires an update to be able to run on the newest firmware.

/WBR Roger

**Comment by ralfvd** [comment]
Hello!

Please install the testversion, which is compatible with Homey 5: https://homey.app/nl-nl/app/com.everspring/Everspring/test/

No repairing of the Z-wave device should be necessary. Please report any findings, so we can make this app better!

Thanks!

**Comment by roger-lindahl** [comment]
Hi!

Thanks, worked Great! 

Wbr Roger

**Comment by roger-lindahl** [comment]
Hi!

Worked Great! /wbr Roger
