### ISSUE TITLE
Still no dimming with AD147

### ISSUE THREAD

**Issue by posthok** [ralfvd/com.everspring#8]
Sorry but the dimmer plug AD147 still not working.With the app version before 1.6 it was possible to dim the light from the device window and wasn't working in a flow. And now in 1.6 it's not dimming from the device windows and within a flow.

**Comment by ralfvd** [comment]
I just tried it with my (temporary) AD147 and the 0.1.6 version installed from the app store, and it is working on my side.

Are you able to run the GitHUb version with the athom-cli in --run mode? If so, please adjust drivers/AD147/driver.js line 9 into debug: true  , run the app and log the output when executing various dim-commands.

You might also want to try a re-pair. That shouldn't make a difference, but you never know.

**Comment by posthok** [comment]
Thanx Ralf, it's working now
